// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 06/06/2026 20:31:24
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/emmay/Documents/GitHub/extra/faso-agri-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emmay/Documents/GitHub/extra/faso-agri-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emmay/Documents/GitHub/extra/faso-agri-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emmay/Documents/GitHub/extra/faso-agri-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emmay/Documents/GitHub/extra/faso-agri-nuxt/plugins/**/*.{js,ts,mjs}","C:/Users/emmay/Documents/GitHub/extra/faso-agri-nuxt/composables/**/*.{js,ts,mjs}","C:/Users/emmay/Documents/GitHub/extra/faso-agri-nuxt/utils/**/*.{js,ts,mjs}","C:/Users/emmay/Documents/GitHub/extra/faso-agri-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emmay/Documents/GitHub/extra/faso-agri-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emmay/Documents/GitHub/extra/faso-agri-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emmay/Documents/GitHub/extra/faso-agri-nuxt/app.config.{js,ts,mjs}","C:/Users/emmay/Documents/GitHub/extra/faso-agri-nuxt/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;